<?php
/**
 * This source file is subject to the rabari.com license that is
 * available through the world-wide-web at this URL:
 * https://www.rabari.com/license-agreement
 */
?>
<div class="rabari-brandslider widget-brandslider">
    <div class="block-title">
        <strong>TOP BRANDS</strong>
    </div>
    <?php
    echo $block->getLayout()->createBlock("Rabari\BrandSlider\Block\BrandSlider")->setData($block->getData())->toHtml();
    ?>
</div>
