<?php
/**
 * This source file is subject to the rabari.com license that is
 * available through the world-wide-web at this URL:
 * https://www.rabari.com/license-agreement
 */
?>
<?php
/** @var \Rabari\BrandSlider\Block\BrandSlider $block */
$htmlId = $block->getFlexSliderHtmlId();
$brandCollection = $block->getBrandCollection();

?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Rabari_BrandSlider::css/flexslider.css') ?>">

<script type="text/javascript">

    (function () {
        // store the slider in a local variable
        require(['jquery', 'rabari/brandslider'], function ($)
        {
            var $window = $(window), flexslider = {vars: {}};
            
            // tiny helper function to add breakpoints
            function getGridSize(itemWidth, itemMargin) {
                return Math.round (jQuery('.rabari-brandslider').width()/(itemWidth + itemMargin));
            }


            $(document).ready(function() {
                var itemWidth = 210, itemMargin = <?= $block->getBrandMargin(); ?>;
                var itemCount = getGridSize(itemWidth, itemMargin);
                itemWidth = Math.round (jQuery('.rabari-brandslider').width()/itemCount);
                
                $(".flex-caption").css({'width' : 'calc(' + itemWidth + 'px - ' + itemMargin + 'px)'});
                
                $('.flexslider').flexslider({
                    animation: "slide",
                    animationLoop: true,
                    pauseOnHover: true,
                    touch: true,
                    itemWidth: itemWidth,
                    slideshow: false,
                    //thumbCaptions: true,
                    itemMargin: itemMargin, /*< ?= //$block->getBrandMargin(); ?>*/
                    minItems: itemCount, // use function to pull in initial value
                    maxItems: itemCount, // use function to pull in initial value
                    <?php
                    if (!$block->getAutoplay()) {
                        echo "slideshow: false, animationLoop: false,";
                    } else {
                        echo 'animation: "slide", slideshow: true, animationLoop: true, slideshowSpeed: ' . $block->getBrandsliderSpeed() . ',';
                    }

                    if (!$block->getDot()) {
                        echo "controlNav: false,";
                    }

                    if (!$block->getNavButton()) {
                        echo "directionNav: false,";
                    }

                    ?>
                    
                });
                //$(".flexslider ul li").addClass("rabari-flex");
                
            });

            // check grid size on resize event
            $window.resize(function () {
                var itemWidth = 210, itemMargin = <?= $block->getBrandMargin(); ?>;
                var itemCount = getGridSize(itemWidth, itemMargin);
                
                flexslider.vars.minItems = itemCount;
                flexslider.vars.maxItems = itemCount;                
            });
        });
    }());

</script>

<div class="rabari-brandslider-standard">
    <?php
    if ($block->getData("show_title")) {

        ?>
        <div class="rabari-content-heading">
            <h2 class="title"><?php echo $block->getTitle(); ?></h2>
        </div>
        <?php
    }

    ?>
    <div class="rabari-brandslider-flex-brandslider">
        <div id="<?php echo $htmlId ?>" class="flexslider carousel flexslider-content-image <?php echo $htmlId ?>" style="margin:auto">
            <ul class="slides">
                <?php
                foreach ($brandCollection as $brand) {

                    ?>
                    <li data-thumb="<?php echo $block->getBrandImageUrl($brand) ?>">
                        <img alt="<?php echo $brand->getImageAlt() ?>" 
                             src="<?php echo $block->getBrandImageUrl($brand) ?>"/>
                            <?php if ($brand->getName() && $block->getShowCaption()) { ?>
                            <div class="flex-caption">
                                <?php echo $brand->getName(); ?>
                            </div>
        <?php } ?>
                    </li>

                    <?php
                }

                ?>
            </ul>
        </div>
    </div>
</div>
